// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"github-setup.mdx": () => import("../content/docs/github-setup.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "archive/clone-starter-repo.mdx": () => import("../content/docs/archive/clone-starter-repo.mdx?collection=docs"), "archive/firebase.mdx": () => import("../content/docs/archive/firebase.mdx?collection=docs"), "archive/gemini.mdx": () => import("../content/docs/archive/gemini.mdx?collection=docs"), "archive/getting-started.mdx": () => import("../content/docs/archive/getting-started.mdx?collection=docs"), "archive/google-auth.mdx": () => import("../content/docs/archive/google-auth.mdx?collection=docs"), "archive/google-cloud.mdx": () => import("../content/docs/archive/google-cloud.mdx?collection=docs"), "archive/google-maps.mdx": () => import("../content/docs/archive/google-maps.mdx?collection=docs"), "archive/idea-submission-form.mdx": () => import("../content/docs/archive/idea-submission-form.mdx?collection=docs"), "archive/starter.mdx": () => import("../content/docs/archive/starter.mdx?collection=docs"), "web-wizard-4.0/index.mdx": () => import("../content/docs/web-wizard-4.0/index.mdx?collection=docs"), "web-wizard-4.0/backend/assignment.mdx": () => import("../content/docs/web-wizard-4.0/backend/assignment.mdx?collection=docs"), "web-wizard-4.0/backend/backend-basics.mdx": () => import("../content/docs/web-wizard-4.0/backend/backend-basics.mdx?collection=docs"), "web-wizard-4.0/backend/backend-overview.mdx": () => import("../content/docs/web-wizard-4.0/backend/backend-overview.mdx?collection=docs"), "web-wizard-4.0/backend/database-and-supabase.mdx": () => import("../content/docs/web-wizard-4.0/backend/database-and-supabase.mdx?collection=docs"), "web-wizard-4.0/backend/express-basics.mdx": () => import("../content/docs/web-wizard-4.0/backend/express-basics.mdx?collection=docs"), "web-wizard-4.0/backend/http-and-rest.mdx": () => import("../content/docs/web-wizard-4.0/backend/http-and-rest.mdx?collection=docs"), "web-wizard-4.0/backend/middleware.mdx": () => import("../content/docs/web-wizard-4.0/backend/middleware.mdx?collection=docs"), "web-wizard-4.0/backend/project-structure.mdx": () => import("../content/docs/web-wizard-4.0/backend/project-structure.mdx?collection=docs"), }),
};
export default browserCollections;