export const domainLeads = [
  {
    id: "1",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    phone_number: "+91-9876543210",
    section: "A",
    branch: "CS",
    domain: "web dev",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh&backgroundColor=b6e3f4",
    profile_links: {
      github: "https://github.com/rajeshkumar",
      linkedin: "https://linkedin.com/in/rajeshkumar",
      twitter: "https://twitter.com/rajeshkumar",
    },
    badges: ["AI Explorer", "Hackathon Hero", "Code Ninja"],
    my_events: ["event-001", "event-002", "event-004"],
    role: "Web Dev Lead",
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-12-10T08:45:00Z",
  },
  {
    id: "2",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    phone_number: "+91-9876543211",
    section: "B",
    branch: "AIML",
    domain: "cp",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya&backgroundColor=ffd6a5",
    profile_links: {
      github: "https://github.com/priyasharma",
      linkedin: "https://linkedin.com/in/priyasharma",
      twitter: null,
    },
    badges: ["Community Lead", "Cloud Certified", "Mentor"],
    my_events: ["event-001", "event-003", "event-005"],
    role: "CP Lead",
    created_at: "2024-02-20T14:20:00Z",
    updated_at: "2024-12-09T16:30:00Z",
  },
  {
    id: "3",
    name: "Arjun Patel",
    email: "arjun.patel@example.com",
    phone_number: "+91-9876543212",
    section: "C",
    branch: "ECS",
    domain: "design",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun&backgroundColor=caffbf",
    profile_links: {
      github: "https://github.com/arjunpatel",
      linkedin: "https://linkedin.com/in/arjunpatel",
      twitter: "https://twitter.com/arjunpatel",
    },
    badges: ["AI Explorer", "Code Ninja"],
    my_events: ["event-002", "event-004"],
    role: "Design Lead",
    created_at: "2024-03-10T09:15:00Z",
    updated_at: "2024-12-08T11:20:00Z",
  },
];

export const teamMembers = [
  // Web Dev Domain
  {
    id: "team-001",
    userid: "user-001",
    domain: "web dev",
    name: "Amit Verma",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amit&backgroundColor=b6e3f4",
    github: "https://github.com/amitverma",
    linkedin: "https://linkedin.com/in/amitverma",
  },
  {
    id: "team-002",
    userid: "user-002",
    domain: "web dev",
    name: "Sakshi Patil",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sakshi&backgroundColor=ffd6a5",
    github: "https://github.com/sakshipatil",
    linkedin: "https://linkedin.com/in/sakshipatil",
  },
  {
    id: "team-003",
    userid: "user-003",
    domain: "web dev",
    name: "Rohan Mehta",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rohan&backgroundColor=caffbf",
    github: "https://github.com/rohanmehta",
    linkedin: "https://linkedin.com/in/rohanmehta",
  },
  
  // CP Domain
  {
    id: "team-004",
    userid: "user-004",
    domain: "cp",
    name: "Neha Agarwal",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Neha&backgroundColor=fdffb6",
    github: "https://github.com/nehaagarwal",
    linkedin: "https://linkedin.com/in/nehaagarwal",
  },
  {
    id: "team-005",
    userid: "user-005",
    domain: "cp",
    name: "Karan Singh",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karan&backgroundColor=ffadad",
    github: "https://github.com/karansingh",
    linkedin: "https://linkedin.com/in/karansingh",
  },
  {
    id: "team-006",
    userid: "user-006",
    domain: "cp",
    name: "Divya Jain",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Divya&backgroundColor=e0c3fc",
    github: "https://github.com/divyajain",
    linkedin: "https://linkedin.com/in/divyajain",
  },
  
  // Design Domain
  {
    id: "team-007",
    userid: "user-007",
    domain: "design",
    name: "Aditya Rao",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aditya&backgroundColor=fde2e4",
    github: "https://github.com/adityarao",
    linkedin: "https://linkedin.com/in/adityarao",
  },
  {
    id: "team-008",
    userid: "user-008",
    domain: "design",
    name: "Isha Khanna",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isha&backgroundColor=d1f7c4",
    github: "https://github.com/ishakhanna",
    linkedin: "https://linkedin.com/in/ishakhanna",
  },
  {
    id: "team-009",
    userid: "user-009",
    domain: "design",
    name: "Varun Kapoor",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Varun&backgroundColor=ffe5ec",
    github: "https://github.com/varunkapoor",
    linkedin: "https://linkedin.com/in/varunkapoor",
  },
  {
    id: "team-010",
    userid: "user-010",
    domain: "design",
    name: "Simran Kaur",
    image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Simran&backgroundColor=faf4b7",
    github: "https://github.com/simrankaur",
    linkedin: "https://linkedin.com/in/simrankaur",
  },
];
