export const teamImg =
  "https://res.cloudinary.com/dlvkywzol/image/upload/v1765395573/WhatsApp_Image_2025-12-11_at_01.06.41_ee2575d7_xtjiwx.jpg";

export const domainLeads = [
  {
    id: "1",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    phone_number: "+91-9876543210",
    section: "A",
    branch: "CS",
    domain: "web dev",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh&backgroundColor=b6e3f4",
    profile_links: {
      github: "https://github.com/rajeshkumar",
      linkedin: "https://linkedin.com/in/rajeshkumar",
      twitter: "https://twitter.com/rajeshkumar",
    },
    badges: ["AI Explorer", "Hackathon Hero", "Code Ninja"],
    my_events: ["event-001", "event-002", "event-004"],
    role: "Web Dev Lead",
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-12-10T08:45:00Z",
  },
  {
    id: "2",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    phone_number: "+91-9876543211",
    section: "B",
    branch: "AIML",
    domain: "cp",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya&backgroundColor=ffd6a5",
    profile_links: {
      github: "https://github.com/priyasharma",
      linkedin: "https://linkedin.com/in/priyasharma",
      twitter: null,
    },
    badges: ["Community Lead", "Cloud Certified", "Mentor"],
    my_events: ["event-001", "event-003", "event-005"],
    role: "CP Lead",
    created_at: "2024-02-20T14:20:00Z",
    updated_at: "2024-12-09T16:30:00Z",
  },
  {
    id: "3",
    name: "Arjun Patel",
    email: "arjun.patel@example.com",
    phone_number: "+91-9876543212",
    section: "C",
    branch: "ECS",
    domain: "design",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun&backgroundColor=caffbf",
    profile_links: {
      github: "https://github.com/arjunpatel",
      linkedin: "https://linkedin.com/in/arjunpatel",
      twitter: "https://twitter.com/arjunpatel",
    },
    badges: ["AI Explorer", "Code Ninja"],
    my_events: ["event-002", "event-004"],
    role: "Design Lead",
    created_at: "2024-03-10T09:15:00Z",
    updated_at: "2024-12-08T11:20:00Z",
  },
];

export const users = [
  {
    id: "user-001",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    phone_number: "+91-9876543210",
    section: "A",
    branch: "CS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh&backgroundColor=b6e3f4",
    profile_links: {
      github: "https://github.com/rajeshkumar",
      linkedin: "https://linkedin.com/in/rajeshkumar",
      twitter: "https://twitter.com/rajeshkumar",
    },
    badges: ["AI Explorer", "Hackathon Hero", "Code Ninja"],
    my_events: ["event-001", "event-002", "event-004"],
    role: "member",
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-12-10T08:45:00Z",
  },
  {
    id: "user-002",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    phone_number: "+91-9876543211",
    section: "B",
    branch: "AIML",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya&backgroundColor=ffd6a5",
    profile_links: {
      github: "https://github.com/priyasharma",
      linkedin: "https://linkedin.com/in/priyasharma",
      twitter: null,
    },
    badges: ["Community Lead", "Cloud Certified", "Mentor"],
    my_events: ["event-001", "event-003", "event-005"],
    role: "lead",
    created_at: "2024-02-20T14:20:00Z",
    updated_at: "2024-12-09T16:30:00Z",
  },
  {
    id: "user-003",
    name: "Arjun Patel",
    email: "arjun.patel@example.com",
    phone_number: "+91-9876543212",
    section: "C",
    branch: "ECS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun&backgroundColor=caffbf",
    profile_links: {
      github: "https://github.com/arjunpatel",
      linkedin: "https://linkedin.com/in/arjunpatel",
      twitter: "https://twitter.com/arjunpatel",
    },
    badges: ["AI Explorer", "Code Ninja"],
    my_events: ["event-002", "event-004"],
    role: "member",
    created_at: "2024-03-10T09:15:00Z",
    updated_at: "2024-12-08T11:20:00Z",
  },
  {
    id: "user-004",
    name: "Sneha Desai",
    email: "sneha.desai@example.com",
    phone_number: "+91-9876543213",
    section: "A",
    branch: "CS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha&backgroundColor=fdffb6",
    profile_links: {
      github: "https://github.com/snehadesai",
      linkedin: "https://linkedin.com/in/snehadesai",
      twitter: null,
    },
    badges: ["Hackathon Hero", "Community Lead"],
    my_events: ["event-001", "event-005"],
    role: "member",
    created_at: "2024-04-05T13:40:00Z",
    updated_at: "2024-12-07T10:15:00Z",
  },
  {
    id: "user-005",
    name: "Vikram Singh",
    email: "vikram.singh@example.com",
    phone_number: "+91-9876543214",
    section: "B",
    branch: "CS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram&backgroundColor=ffadad",
    profile_links: {
      github: "https://github.com/vikramsingh",
      linkedin: "https://linkedin.com/in/vikramsingh",
      twitter: "https://twitter.com/vikramsingh",
    },
    badges: ["Cloud Certified", "Mentor"],
    my_events: ["event-003", "event-004"],
    role: "co-lead",
    created_at: "2024-05-12T11:25:00Z",
    updated_at: "2024-12-06T14:50:00Z",
  },
  {
    id: "user-006",
    name: "Neha Verma",
    email: "neha.verma@example.com",
    phone_number: "+91-9876543220",
    section: "C",
    branch: "CS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Neha&backgroundColor=e0c3fc",
    profile_links: {
      github: "https://github.com/nehaverma",
      linkedin: "https://linkedin.com/in/nehaverma",
      twitter: null,
    },
    badges: ["Community Lead"],
    my_events: ["event-003", "event-006"],
    role: "member",
    created_at: "2024-06-01T10:00:00Z",
    updated_at: "2024-12-05T11:00:00Z",
  },
  {
    id: "user-007",
    name: "Aman Joshi",
    email: "aman.joshi@example.com",
    phone_number: "+91-9876543221",
    section: "A",
    branch: "AIML",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Aman&backgroundColor=fde2e4",
    profile_links: {
      github: "https://github.com/amanjoshi",
      linkedin: "https://linkedin.com/in/amanjoshi",
      twitter: null,
    },
    badges: ["Code Ninja"],
    my_events: ["event-004", "event-007"],
    role: "member",
    created_at: "2024-06-15T09:00:00Z",
    updated_at: "2024-12-02T13:20:00Z",
  },
  {
    id: "user-008",
    name: "Riya Gupta",
    email: "riya.gupta@example.com",
    phone_number: "+91-9876543222",
    section: "B",
    branch: "AIML",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Riya&backgroundColor=d1f7c4",
    profile_links: {
      github: "https://github.com/riyagupta",
      linkedin: "https://linkedin.com/in/riyagupta",
      twitter: "https://twitter.com/riyagupta",
    },
    badges: ["AI Explorer", "Mentor"],
    my_events: ["event-002", "event-005", "event-008"],
    role: "co-lead",
    created_at: "2024-07-01T11:30:00Z",
    updated_at: "2024-12-08T16:10:00Z",
  },
  {
    id: "user-009",
    name: "Kunal Shah",
    email: "kunal.shah@example.com",
    phone_number: "+91-9876543223",
    section: "C",
    branch: "CS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Kunal&backgroundColor=ffe5ec",
    profile_links: {
      github: "https://github.com/kunalshah",
      linkedin: "https://linkedin.com/in/kunalshah",
      twitter: null,
    },
    badges: ["Hackathon Hero"],
    my_events: ["event-004", "event-007", "event-011"],
    role: "member",
    created_at: "2024-07-18T08:45:00Z",
    updated_at: "2024-12-04T09:25:00Z",
  },
  {
    id: "user-010",
    name: "Shruti Pandey",
    email: "shruti.pandey@example.com",
    phone_number: "+91-9876543224",
    section: "A",
    branch: "CS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Shruti&backgroundColor=faf4b7",
    profile_links: {
      github: "https://github.com/shrutipandey",
      linkedin: "https://linkedin.com/in/shrutipandey",
      twitter: "https://twitter.com/shrutipandey",
    },
    badges: ["Cloud Certified", "AI Explorer"],
    my_events: ["event-003", "event-005", "event-012"],
    role: "member",
    created_at: "2024-08-02T12:10:00Z",
    updated_at: "2024-12-06T15:40:00Z",
  },
  {
    id: "user-011",
    name: "Harsh Yadav",
    email: "harsh.yadav@example.com",
    phone_number: "+91-9876543225",
    section: "B",
    branch: "ECS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Harsh&backgroundColor=cde7ff",
    profile_links: {
      github: "https://github.com/harshyadav",
      linkedin: "https://linkedin.com/in/harshyadav",
      twitter: null,
    },
    badges: ["Code Ninja", "Hackathon Hero"],
    my_events: ["event-002", "event-004", "event-009"],
    role: "member",
    created_at: "2024-08-20T10:00:00Z",
    updated_at: "2024-12-03T18:00:00Z",
  },
  {
    id: "user-012",
    name: "Pooja Malhotra",
    email: "pooja.malhotra@example.com",
    phone_number: "+91-9876543226",
    section: "C",
    branch: "AIML",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Pooja&backgroundColor=e5d9f2",
    profile_links: {
      github: "https://github.com/poojamalhotra",
      linkedin: "https://linkedin.com/in/poojamalhotra",
      twitter: "https://twitter.com/poojamalhotra",
    },
    badges: ["Mentor", "Community Lead"],
    my_events: ["event-001", "event-003", "event-011"],
    role: "lead",
    created_at: "2024-09-01T09:30:00Z",
    updated_at: "2024-12-07T11:45:00Z",
  },
  {
    id: "user-013",
    name: "Tanmay Kulkarni",
    email: "tanmay.kulkarni@example.com",
    phone_number: "+91-9876543227",
    section: "A",
    branch: "CS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Tanmay&backgroundColor=d0f4de",
    profile_links: {
      github: "https://github.com/tanmaykulkarni",
      linkedin: "https://linkedin.com/in/tanmaykulkarni",
      twitter: null,
    },
    badges: ["AI Explorer", "Code Ninja"],
    my_events: ["event-002", "event-006", "event-013"],
    role: "member",
    created_at: "2024-09-10T14:00:00Z",
    updated_at: "2024-12-09T17:10:00Z",
  },
  {
    id: "user-014",
    name: "Ishaan Roy",
    email: "ishaan.roy@example.com",
    phone_number: "+91-9876543228",
    section: "B",
    branch: "AIDS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Ishaan&backgroundColor=ffeedd",
    profile_links: {
      github: "https://github.com/ishaanroy",
      linkedin: "https://linkedin.com/in/ishaanroy",
      twitter: "https://twitter.com/ishaanroy",
    },
    badges: ["AI Explorer"],
    my_events: ["event-002", "event-014"],
    role: "member",
    created_at: "2024-09-22T16:30:00Z",
    updated_at: "2024-12-08T12:25:00Z",
  },
  {
    id: "user-015",
    name: "Simran Kaur",
    email: "simran.kaur@example.com",
    phone_number: "+91-9876543229",
    section: "C",
    branch: "CS",
    image_url:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Simran&backgroundColor=fdebd3",
    profile_links: {
      github: "https://github.com/simrankaur",
      linkedin: "https://linkedin.com/in/simrankaur",
      twitter: null,
    },
    badges: ["Cloud Certified", "Mentor"],
    my_events: ["event-003", "event-005", "event-015"],
    role: "co-lead",
    created_at: "2024-10-01T13:15:00Z",
    updated_at: "2024-12-10T09:00:00Z",
  },
];
export const events = [
  {
    id: "event-001",
    title: "SpiderCraft 2025",
    description:
      "SPIDER CRAFT 2025: WHERE TECH MET FUN! An immersive workshop combining web development with creative design, inspired by the Spider-Verse aesthetic. Learn modern web technologies while building amazing projects.",
    event_time: "2024-11-12T14:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=2070&auto=format&fit=crop",
    tags: ["Web Development", "Workshop"],
    tag_color: "#FFC20E",
    location: "Main Auditorium, RBU Campus",
    capacity: 150,
    registered_count: 128,
    status: "completed",
    created_at: "2024-10-01T10:00:00Z",
  },
  {
    id: "event-002",
    title: "AI/ML Bootcamp",
    description:
      "Dive deep into Artificial Intelligence and Machine Learning fundamentals. Hands-on sessions covering neural networks, deep learning, and practical AI applications. Perfect for beginners and intermediate learners.",
    event_time: "2024-10-25T10:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1555255707-c07966088b7b?q=80&w=2070&auto=format&fit=crop",
    tags: ["Artificial Intelligence", "Machine Learning"],
    tag_color: "#4285F4",
    location: "Computer Lab 3, Building A",
    capacity: 80,
    registered_count: 75,
    status: "completed",
    created_at: "2024-09-15T09:00:00Z",
  },
  {
    id: "event-003",
    title: "Cloud Computing Workshop",
    description:
      "Master cloud technologies with Google Cloud Platform. Learn about cloud architecture, deployment strategies, serverless computing, and best practices for building scalable applications.",
    event_time: "2024-09-18T15:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop",
    tags: ["Cloud Computing", "GCP"],
    tag_color: "#34A853",
    location: "Seminar Hall 2",
    capacity: 100,
    registered_count: 92,
    status: "completed",
    created_at: "2024-08-20T11:00:00Z",
  },
  {
    id: "event-004",
    title: "Android Development Hackathon",
    description:
      "24-hour hackathon focused on Android app development. Build innovative mobile solutions, compete with peers, and win exciting prizes. Mentorship from industry experts included.",
    event_time: "2024-08-05T09:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?q=80&w=2070&auto=format&fit=crop",
    tags: ["Android", "Hackathon"],
    tag_color: "#EA4335",
    location: "Innovation Center",
    capacity: 120,
    registered_count: 115,
    status: "completed",
    created_at: "2024-07-10T10:00:00Z",
  },
  {
    id: "event-005",
    title: "DevFest Nagpur 2025",
    description:
      "The biggest developer festival of the year! Join us for a day of learning, networking, and celebrating technology. Featuring keynote speakers, technical sessions, workshops, and community connections.",
    event_time: "2025-01-15T09:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=2070&auto=format&fit=crop",
    tags: ["Conference", "Upcoming"],
    tag_color: "#FBBC04",
    location: "Grand Convention Center, Nagpur",
    capacity: 500,
    registered_count: 342,
    status: "upcoming",
    entry_fee: "₹299",
    created_at: "2024-11-01T10:00:00Z",
  },
  {
    id: "event-006",
    title: "Flutter Forward Workshop",
    description:
      "Build beautiful, natively compiled applications for mobile, web, and desktop from a single codebase using Flutter. Learn widgets, state management, and deployment strategies.",
    event_time: "2025-02-10T14:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=2070&auto=format&fit=crop",
    tags: ["Flutter", "Mobile Development"],
    tag_color: "#02569B",
    location: "Lab 5, IT Block",
    capacity: 60,
    registered_count: 45,
    status: "completed",
    created_at: "2024-12-01T09:00:00Z",
  },
  // Add to `events`
  {
    id: "event-007",
    title: "DSA Marathon 2024",
    description:
      "An intensive problem-solving marathon focused on data structures and algorithms with live mentoring.",
    event_time: "2024-08-30T10:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    tags: ["DSA", "Competitive Programming"],
    tag_color: "#9B59B6",
    location: "Computer Lab 1",
    capacity: 90,
    registered_count: 82,
    status: "completed",
    created_at: "2024-07-20T10:00:00Z",
  },
  {
    id: "event-008",
    title: "Git & Open Source Jam",
    description:
      "Hands-on workshop to learn Git, GitHub workflows, and contribute to real open-source projects.",
    event_time: "2024-09-10T11:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=2070&auto=format&fit=crop",
    tags: ["Open Source", "Tools"],
    tag_color: "#2ECC71",
    location: "Innovation Lab",
    capacity: 70,
    registered_count: 64,
    status: "completed",
    created_at: "2024-08-05T12:00:00Z",
  },
  {
    id: "event-009",
    title: "Women in Tech Panel",
    description:
      "Inspiring panel discussion featuring women leaders in technology sharing their journeys and insights.",
    event_time: "2024-10-10T15:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1551836022-4c4c79ecde5e?q=80&w=2070&auto=format&fit=crop",
    tags: ["Diversity", "Panel Discussion"],
    tag_color: "#F39C12",
    location: "Main Auditorium",
    capacity: 200,
    registered_count: 176,
    status: "completed",
    created_at: "2024-09-01T10:30:00Z",
  },
  {
    id: "event-010",
    title: "DevOps for Beginners",
    description:
      "Introduction to CI/CD, containers, and monitoring with hands-on demos using modern DevOps tools.",
    event_time: "2024-11-05T09:30:00Z",
    image_url:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    tags: ["DevOps", "Cloud"],
    tag_color: "#1ABC9C",
    location: "Seminar Hall 3",
    capacity: 80,
    registered_count: 74,
    status: "completed",
    created_at: "2024-09-25T09:00:00Z",
  },
  {
    id: "event-011",
    title: "Web3 Hack Night",
    description:
      "Build decentralized applications, smart contracts, and experiment with blockchain tools in a night-long hack.",
    event_time: "2025-02-01T17:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    tags: ["Blockchain", "Hackathon"],
    tag_color: "#8E44AD",
    location: "Innovation Center",
    capacity: 100,
    registered_count: 68,
    status: "completed",
    created_at: "2024-11-20T12:00:00Z",
  },
  {
    id: "event-012",
    title: "AR/VR Experience Lab",
    description:
      "Hands-on experience building immersive applications with ARCore and WebXR.",
    event_time: "2025-02-20T13:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1581090700227-1e37b190418e?q=80&w=2070&auto=format&fit=crop",
    tags: ["AR/VR", "Experiential"],
    tag_color: "#E74C3C",
    location: "XR Studio",
    capacity: 50,
    registered_count: 37,
    status: "completed",
    created_at: "2024-11-28T11:00:00Z",
  },
  {
    id: "event-013",
    title: "GDSC x GDG Dev Summit",
    description:
      "Collaborative summit featuring talks, lightning sessions, and networking across multiple campuses.",
    event_time: "2025-03-01T09:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1503428593586-e225b39bddfe?q=80&w=2070&auto=format&fit=crop",
    tags: ["Conference", "Collaboration"],
    tag_color: "#3498DB",
    location: "Convention Hall",
    capacity: 400,
    registered_count: 265,
    status: "completed",
    created_at: "2024-12-02T10:30:00Z",
  },
  {
    id: "event-014",
    title: "Data Analytics Bootcamp",
    description:
      "Bootcamp focused on data analysis, visualization, and dashboards using Python and popular BI tools.",
    event_time: "2025-03-10T10:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=2070&auto=format&fit=crop",
    tags: ["Data", "Analytics"],
    tag_color: "#9B59B6",
    location: "Lab 2, Analytics Block",
    capacity: 70,
    registered_count: 49,
    status: "completed",
    created_at: "2024-12-05T09:45:00Z",
  },
  {
    id: "event-015",
    title: "Kotlin Conf: Campus Edition",
    description:
      "Kotlin-focused event covering Android, multiplatform, and backend development with live coding sessions.",
    event_time: "2025-03:25T11:00:00Z".replace(":", "-"), // fix if needed in real code
    image_url:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    tags: ["Kotlin", "Android"],
    tag_color: "#16A085",
    location: "Android Lab",
    capacity: 60,
    registered_count: 38,
    status: "completed",
    created_at: "2024-12-07T12:15:00Z",
  },
  {
    id: "event-016",
    title: "TensorFlow Lite on Edge",
    description:
      "Workshop on deploying ML models to mobile and embedded devices using TensorFlow Lite.",
    event_time: "2025-04-05T14:00:00Z",
    image_url:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    tags: ["Machine Learning", "Edge AI"],
    tag_color: "#F1C40F",
    location: "Embedded Systems Lab",
    capacity: 50,
    registered_count: 27,
    status: "upcoming",
    entry_fee: "₹149",
    created_at: "2024-12-10T08:30:00Z",
  },
];
export const registrations = [
  {
    id: "reg-001",
    user_id: "user-001",
    event_id: "event-001",
    status: "checked_in",
    created_at: "2024-11-01T10:30:00Z",
    checked_in_at: "2024-11-12T13:45:00Z",
  },
  {
    id: "reg-002",
    user_id: "user-001",
    event_id: "event-002",
    status: "checked_in",
    created_at: "2024-10-15T14:20:00Z",
    checked_in_at: "2024-10-25T09:50:00Z",
  },
  {
    id: "reg-003",
    user_id: "user-001",
    event_id: "event-004",
    status: "checked_in",
    created_at: "2024-07-20T11:15:00Z",
    checked_in_at: "2024-08-05T08:55:00Z",
  },
  {
    id: "reg-004",
    user_id: "user-002",
    event_id: "event-001",
    status: "checked_in",
    created_at: "2024-11-02T09:45:00Z",
    checked_in_at: "2024-11-12T13:50:00Z",
  },
  {
    id: "reg-005",
    user_id: "user-002",
    event_id: "event-003",
    status: "checked_in",
    created_at: "2024-09-05T15:30:00Z",
    checked_in_at: "2024-09-18T14:45:00Z",
  },
  {
    id: "reg-006",
    user_id: "user-002",
    event_id: "event-005",
    status: "registered",
    created_at: "2024-11-10T10:20:00Z",
    checked_in_at: null,
  },
  {
    id: "reg-007",
    user_id: "user-003",
    event_id: "event-002",
    status: "checked_in",
    created_at: "2024-10-18T13:40:00Z",
    checked_in_at: "2024-10-25T09:55:00Z",
  },
  {
    id: "reg-008",
    user_id: "user-003",
    event_id: "event-004",
    status: "checked_in",
    created_at: "2024-07-22T10:30:00Z",
    checked_in_at: "2024-08-05T09:00:00Z",
  },
  {
    id: "reg-009",
    user_id: "user-004",
    event_id: "event-001",
    status: "registered",
    created_at: "2024-11-08T12:15:00Z",
    checked_in_at: null,
  },
  {
    id: "reg-010",
    user_id: "user-004",
    event_id: "event-005",
    status: "registered",
    created_at: "2024-11-12T14:30:00Z",
    checked_in_at: null,
  },
  {
    id: "reg-011",
    user_id: "user-005",
    event_id: "event-003",
    status: "checked_in",
    created_at: "2024-09-08T11:20:00Z",
    checked_in_at: "2024-09-18T14:50:00Z",
  },
  {
    id: "reg-012",
    user_id: "user-005",
    event_id: "event-004",
    status: "checked_in",
    created_at: "2024-07-25T09:45:00Z",
    checked_in_at: "2024-08-05T09:05:00Z",
  },
  // Add to `registrations`
  {
    id: "reg-013",
    user_id: "user-006",
    event_id: "event-003",
    status: "checked_in",
    created_at: "2024-08-25T10:10:00Z",
    checked_in_at: "2024-09-18T14:55:00Z",
  },
  {
    id: "reg-014",
    user_id: "user-007",
    event_id: "event-004",
    status: "checked_in",
    created_at: "2024-07-26T10:15:00Z",
    checked_in_at: "2024-08-05T09:10:00Z",
  },
  {
    id: "reg-015",
    user_id: "user-008",
    event_id: "event-002",
    status: "checked_in",
    created_at: "2024-10-10T09:30:00Z",
    checked_in_at: "2024-10-25T09:45:00Z",
  },
  {
    id: "reg-016",
    user_id: "user-009",
    event_id: "event-007",
    status: "checked_in",
    created_at: "2024-08-20T09:55:00Z",
    checked_in_at: "2024-08-30T09:50:00Z",
  },
  {
    id: "reg-017",
    user_id: "user-010",
    event_id: "event-003",
    status: "checked_in",
    created_at: "2024-09-05T11:40:00Z",
    checked_in_at: "2024-09-18T14:40:00Z",
  },
  {
    id: "reg-018",
    user_id: "user-011",
    event_id: "event-009",
    status: "checked_in",
    created_at: "2024-09-20T13:10:00Z",
    checked_in_at: "2024-10-10T14:55:00Z",
  },
  {
    id: "reg-019",
    user_id: "user-012",
    event_id: "event-011",
    status: "registered",
    created_at: "2024-12-03T15:00:00Z",
    checked_in_at: null,
  },
  {
    id: "reg-020",
    user_id: "user-013",
    event_id: "event-006",
    status: "registered",
    created_at: "2024-12-04T12:20:00Z",
    checked_in_at: null,
  },
  {
    id: "reg-021",
    user_id: "user-014",
    event_id: "event-014",
    status: "registered",
    created_at: "2024-12-06T09:15:00Z",
    checked_in_at: null,
  },
  {
    id: "reg-022",
    user_id: "user-015",
    event_id: "event-015",
    status: "registered",
    created_at: "2024-12-08T10:25:00Z",
    checked_in_at: null,
  },
];
export const team_members = [
  {
    id: "team-001",
    name: "Aditya Mehta",
    role: "GDG Lead",
    email: "aditya.mehta@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/adityamehta",
    linkedin_url: "https://linkedin.com/in/adityamehta",
    bio: "Passionate about building developer communities and fostering innovation. Leading GDG on Campus to empower students with cutting-edge technology.",
    department: "Computer Science",
    year: "Final Year",
  },
  {
    id: "team-002",
    name: "Kavya Reddy",
    role: "Co-Lead & Event Manager",
    email: "kavya.reddy@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/kavyareddy",
    linkedin_url: "https://linkedin.com/in/kavyareddy",
    bio: "Expert in organizing tech events and workshops. Committed to creating engaging learning experiences for the developer community.",
    department: "Information Technology",
    year: "Third Year",
  },
  {
    id: "team-003",
    name: "Rohan Kapoor",
    role: "Technical Lead",
    email: "rohan.kapoor@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/rohankapoor",
    linkedin_url: "https://linkedin.com/in/rohankapoor",
    bio: "Full-stack developer with expertise in cloud technologies. Leading technical workshops and mentoring students in modern development practices.",
    department: "Computer Science",
    year: "Final Year",
  },
  {
    id: "team-004",
    name: "Ananya Iyer",
    role: "Design Lead",
    email: "ananya.iyer@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/ananyaiyer",
    linkedin_url: "https://linkedin.com/in/ananyaiyer",
    bio: "UI/UX designer passionate about creating intuitive and beautiful user experiences. Leading design initiatives for GDG projects.",
    department: "Design",
    year: "Third Year",
  },
  {
    id: "team-005",
    name: "Karthik Nair",
    role: "Marketing Lead",
    email: "karthik.nair@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/karthiknair",
    linkedin_url: "https://linkedin.com/in/karthiknair",
    bio: "Digital marketing enthusiast driving community engagement and outreach. Building GDG's online presence and connecting with developers.",
    department: "Business Administration",
    year: "Third Year",
  },
  {
    id: "team-006",
    name: "Ishita Bhatt",
    role: "Content Lead",
    email: "ishita.bhatt@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/ishitabhatt",
    linkedin_url: "https://linkedin.com/in/ishitabhatt",
    bio: "Tech writer and content creator. Crafting compelling stories about technology and sharing knowledge through blogs and documentation.",
    department: "Computer Science",
    year: "Second Year",
  },
  {
    id: "team-007",
    name: "Siddharth Joshi",
    role: "Android Lead",
    email: "siddharth.joshi@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/siddharthjoshi",
    linkedin_url: "https://linkedin.com/in/siddharthjoshi",
    bio: "Android developer specializing in Kotlin and Jetpack Compose. Conducting mobile development workshops and building innovative apps.",
    department: "Computer Science",
    year: "Third Year",
  },
  {
    id: "team-008",
    name: "Meera Kulkarni",
    role: "Cloud & DevOps Lead",
    email: "meera.kulkarni@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/meerakulkarni",
    linkedin_url: "https://linkedin.com/in/meerakulkarni",
    bio: "Cloud enthusiast focused on Google Cloud Platform and DevOps practices. Teaching infrastructure as code and cloud-native development.",
    department: "Information Technology",
    year: "Final Year",
  },
  // Add to `team_members`
  {
    id: "team-009",
    name: "Pooja Malhotra",
    role: "AI Lead",
    email: "pooja.malhotra@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/poojamalhotra",
    linkedin_url: "https://linkedin.com/in/poojamalhotra",
    bio: "Machine learning enthusiast working on real-time AI solutions and student mentoring.",
    department: "Computer Science",
    year: "Final Year",
  },
  {
    id: "team-010",
    name: "Varun Saxena",
    role: "Web Lead",
    email: "varun.saxena@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/varunsaxena",
    linkedin_url: "https://linkedin.com/in/varunsaxena",
    bio: "Full-stack web developer focusing on performance and accessibility.",
    department: "Information Technology",
    year: "Third Year",
  },
  {
    id: "team-011",
    name: "Sneha Jain",
    role: "Community Manager",
    email: "sneha.jain@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/snehajain",
    linkedin_url: "https://linkedin.com/in/snehajain",
    bio: "Building inclusive tech communities and hosting interactive sessions.",
    department: "Computer Science",
    year: "Second Year",
  },
  {
    id: "team-012",
    name: "Rahul Nair",
    role: "Backend Lead",
    email: "rahul.nair@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/rahulnair",
    linkedin_url: "https://linkedin.com/in/rahulnair",
    bio: "API design, databases, and server-side optimization fanboy.",
    department: "Computer Science",
    year: "Final Year",
  },
  {
    id: "team-013",
    name: "Anjali Singh",
    role: "Outreach Lead",
    email: "anjali.singh@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/anjalisingh",
    linkedin_url: "https://linkedin.com/in/anjalisingh",
    bio: "Connecting with colleges, clubs, and partners to grow the community.",
    department: "Business Administration",
    year: "Third Year",
  },
  {
    id: "team-014",
    name: "Ritik Sharma",
    role: "Logistics Lead",
    email: "ritik.sharma@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/ritiksharma",
    linkedin_url: "https://linkedin.com/in/ritiksharma",
    bio: "Ensuring events run smoothly from registrations to snacks.",
    department: "Mechanical Engineering",
    year: "Third Year",
  },
  {
    id: "team-015",
    name: "Muskan Arora",
    role: "Social Media Lead",
    email: "muskan.arora@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/muskanarora",
    linkedin_url: "https://linkedin.com/in/muskanarora",
    bio: "Telling the community story through visuals, reels, and content.",
    department: "Design",
    year: "Second Year",
  },
  {
    id: "team-016",
    name: "Adarsh Mishra",
    role: "IoT Lead",
    email: "adarsh.mishra@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/adarshmishra",
    linkedin_url: "https://linkedin.com/in/adarshmishra",
    bio: "Building smart systems connecting hardware and cloud.",
    department: "Electronics Engineering",
    year: "Final Year",
  },
  {
    id: "team-017",
    name: "Sanya Deshpande",
    role: "Video & Media Lead",
    email: "sanya.deshpande@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/sanyadeshpande",
    linkedin_url: "https://linkedin.com/in/sanyadeshpande",
    bio: "Documenting events and building the visual brand of GDG.",
    department: "Media Studies",
    year: "Third Year",
  },
  {
    id: "team-018",
    name: "Arpit Jain",
    role: "Operations Lead",
    email: "arpit.jain@gdg.com",
    image_url:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=387&auto=format&fit=crop",
    github_url: "https://github.com/arpitjain",
    linkedin_url: "https://linkedin.com/in/arpitjain",
    bio: "Bridging planning and execution for all community initiatives.",
    department: "Computer Science",
    year: "Final Year",
  },
];
export const badges = [
  {
    id: "badge-001",
    name: "AI Explorer",
    description:
      "Completed AI/ML workshops and demonstrated understanding of artificial intelligence concepts",
    icon: "Cloud",
    color: "bg-blue-100 dark:bg-blue-900/30",
    icon_color: "text-blue-500",
    criteria: "Attend at least 2 AI/ML events",
    rarity: "common",
  },
  {
    id: "badge-002",
    name: "Hackathon Hero",
    description:
      "Participated in hackathons and showcased problem-solving skills through innovative projects",
    icon: "Trophy",
    color: "bg-red-100 dark:bg-red-900/30",
    icon_color: "text-red-500",
    criteria: "Complete a hackathon project",
    rarity: "rare",
  },
  {
    id: "badge-003",
    name: "Community Lead",
    description:
      "Demonstrated leadership in the GDG community by organizing events and mentoring peers",
    icon: "UserCheck",
    color: "bg-yellow-100 dark:bg-yellow-900/30",
    icon_color: "text-yellow-600",
    criteria: "Organize or lead 3+ community events",
    rarity: "epic",
  },
  {
    id: "badge-004",
    name: "Cloud Certified",
    description:
      "Achieved proficiency in cloud computing platforms and best practices",
    icon: "Award",
    color: "bg-green-100 dark:bg-green-900/30",
    icon_color: "text-green-500",
    criteria: "Complete cloud computing workshops",
    rarity: "rare",
  },
  {
    id: "badge-005",
    name: "Code Ninja",
    description:
      "Mastered coding skills through multiple technical workshops and projects",
    icon: "Code",
    color: "bg-purple-100 dark:bg-purple-900/30",
    icon_color: "text-purple-500",
    criteria: "Attend 5+ technical workshops",
    rarity: "common",
  },
  {
    id: "badge-006",
    name: "Mentor",
    description:
      "Guided and supported fellow community members in their learning journey",
    icon: "Share2",
    color: "bg-orange-100 dark:bg-orange-900/30",
    icon_color: "text-orange-500",
    criteria: "Mentor at least 5 community members",
    rarity: "epic",
  },
  // Add to `badges`
  {
    id: "badge-007",
    name: "Open Source Contributor",
    description:
      "Contributed to open-source repositories and collaborated with the community.",
    icon: "GitBranch",
    color: "bg-indigo-100 dark:bg-indigo-900/30",
    icon_color: "text-indigo-500",
    criteria: "Open at least 3 meaningful pull requests",
    rarity: "rare",
  },
  {
    id: "badge-008",
    name: "Event Organizer",
    description:
      "Planned and executed successful community events with high engagement.",
    icon: "Calendar",
    color: "bg-teal-100 dark:bg-teal-900/30",
    icon_color: "text-teal-500",
    criteria: "Organize at least 2 events",
    rarity: "epic",
  },
  {
    id: "badge-009",
    name: "Speaker",
    description: "Delivered technical talks or sessions at GDG events.",
    icon: "Mic",
    color: "bg-yellow-100 dark:bg-yellow-900/30",
    icon_color: "text-yellow-500",
    criteria: "Speak at 1+ events",
    rarity: "rare",
  },
  {
    id: "badge-010",
    name: "Design Warrior",
    description:
      "Outstanding performance in UI/UX design sprints and workshops.",
    icon: "Palette",
    color: "bg-pink-100 dark:bg-pink-900/30",
    icon_color: "text-pink-500",
    criteria: "Participate in 2+ design events",
    rarity: "rare",
  },
  {
    id: "badge-011",
    name: "Cloud Champion",
    description: "Showcased advanced understanding of cloud-native solutions.",
    icon: "CloudLightning",
    color: "bg-sky-100 dark:bg-sky-900/30",
    icon_color: "text-sky-500",
    criteria: "Build and demo a cloud project",
    rarity: "epic",
  },
  {
    id: "badge-012",
    name: "Hackathon Finalist",
    description: "Reached the final judging round in a major hackathon.",
    icon: "Medal",
    color: "bg-gray-100 dark:bg-gray-800/30",
    icon_color: "text-gray-600",
    criteria: "Qualify as finalist in a hackathon",
    rarity: "rare",
  },
  {
    id: "badge-013",
    name: "Community Star",
    description: "Recognized for consistent engagement and helping peers.",
    icon: "Star",
    color: "bg-amber-100 dark:bg-amber-900/30",
    icon_color: "text-amber-500",
    criteria: "Help at least 10 members",
    rarity: "epic",
  },
  {
    id: "badge-014",
    name: "Bug Hunter",
    description: "Found and reported critical bugs in community projects.",
    icon: "Bug",
    color: "bg-red-100 dark:bg-red-900/30",
    icon_color: "text-red-500",
    criteria: "Report 5+ valid bugs",
    rarity: "common",
  },
  {
    id: "badge-015",
    name: "Doc Master",
    description:
      "Created or improved documentation for community repositories.",
    icon: "FileText",
    color: "bg-slate-100 dark:bg-slate-900/30",
    icon_color: "text-slate-500",
    criteria: "Write or improve 3+ docs",
    rarity: "common",
  },
  {
    id: "badge-016",
    name: "Workshop Mentor",
    description: "Helped participants during hands-on workshops and labs.",
    icon: "Users",
    color: "bg-lime-100 dark:bg-lime-900/30",
    icon_color: "text-lime-500",
    criteria: "Mentor in 2+ workshops",
    rarity: "epic",
  },
];
export const certificates = [
  {
    id: "cert-001",
    user_id: "user-001",
    event_id: "event-001",
    certificate_url:
      "https://certificates.gdg.com/spidercraft-2025/user-001.pdf",
    issued_at: "2024-11-15T10:00:00Z",
    certificate_number: "GDG-SC25-001",
    template: "spidercraft_2025",
  },
  {
    id: "cert-002",
    user_id: "user-001",
    event_id: "event-002",
    certificate_url: "https://certificates.gdg.com/ai-ml-bootcamp/user-001.pdf",
    issued_at: "2024-10-28T10:00:00Z",
    certificate_number: "GDG-AIML-001",
    template: "ai_ml_bootcamp",
  },
  {
    id: "cert-003",
    user_id: "user-001",
    event_id: "event-004",
    certificate_url:
      "https://certificates.gdg.com/android-hackathon/user-001.pdf",
    issued_at: "2024-08-08T10:00:00Z",
    certificate_number: "GDG-ANHACK-001",
    template: "android_hackathon",
  },
  {
    id: "cert-004",
    user_id: "user-002",
    event_id: "event-001",
    certificate_url:
      "https://certificates.gdg.com/spidercraft-2025/user-002.pdf",
    issued_at: "2024-11-15T10:00:00Z",
    certificate_number: "GDG-SC25-002",
    template: "spidercraft_2025",
  },
  {
    id: "cert-005",
    user_id: "user-002",
    event_id: "event-003",
    certificate_url: "https://certificates.gdg.com/cloud-workshop/user-002.pdf",
    issued_at: "2024-09-21T10:00:00Z",
    certificate_number: "GDG-CLOUD-002",
    template: "cloud_computing",
  },
  {
    id: "cert-006",
    user_id: "user-003",
    event_id: "event-002",
    certificate_url: "https://certificates.gdg.com/ai-ml-bootcamp/user-003.pdf",
    issued_at: "2024-10-28T10:00:00Z",
    certificate_number: "GDG-AIML-003",
    template: "ai_ml_bootcamp",
  },
  {
    id: "cert-007",
    user_id: "user-003",
    event_id: "event-004",
    certificate_url:
      "https://certificates.gdg.com/android-hackathon/user-003.pdf",
    issued_at: "2024-08-08T10:00:00Z",
    certificate_number: "GDG-ANHACK-003",
    template: "android_hackathon",
  },
  {
    id: "cert-008",
    user_id: "user-005",
    event_id: "event-003",
    certificate_url: "https://certificates.gdg.com/cloud-workshop/user-005.pdf",
    issued_at: "2024-09-21T10:00:00Z",
    certificate_number: "GDG-CLOUD-005",
    template: "cloud_computing",
  },
  {
    id: "cert-009",
    user_id: "user-005",
    event_id: "event-004",
    certificate_url:
      "https://certificates.gdg.com/android-hackathon/user-005.pdf",
    issued_at: "2024-08-08T10:00:00Z",
    certificate_number: "GDG-ANHACK-005",
    template: "android_hackathon",
  },
  // Add to `certificates`
  {
    id: "cert-010",
    user_id: "user-002",
    event_id: "event-004",
    certificate_url:
      "https://certificates.gdg.com/android-hackathon/user-002.pdf",
    issued_at: "2024-08-09T10:00:00Z",
    certificate_number: "GDG-ANHACK-002",
    template: "android_hackathon",
  },
  {
    id: "cert-011",
    user_id: "user-006",
    event_id: "event-003",
    certificate_url: "https://certificates.gdg.com/cloud-workshop/user-006.pdf",
    issued_at: "2024-09-22T10:00:00Z",
    certificate_number: "GDG-CLOUD-006",
    template: "cloud_computing",
  },
  {
    id: "cert-012",
    user_id: "user-007",
    event_id: "event-004",
    certificate_url:
      "https://certificates.gdg.com/android-hackathon/user-007.pdf",
    issued_at: "2024-08-09T10:00:00Z",
    certificate_number: "GDG-ANHACK-007",
    template: "android_hackathon",
  },
  {
    id: "cert-013",
    user_id: "user-008",
    event_id: "event-002",
    certificate_url: "https://certificates.gdg.com/ai-ml-bootcamp/user-008.pdf",
    issued_at: "2024-10-29T10:00:00Z",
    certificate_number: "GDG-AIML-008",
    template: "ai_ml_bootcamp",
  },
  {
    id: "cert-014",
    user_id: "user-009",
    event_id: "event-007",
    certificate_url: "https://certificates.gdg.com/dsa-marathon/user-009.pdf",
    issued_at: "2024-09-02T10:00:00Z",
    certificate_number: "GDG-DSA-009",
    template: "dsa_marathon",
  },
  {
    id: "cert-015",
    user_id: "user-010",
    event_id: "event-003",
    certificate_url: "https://certificates.gdg.com/cloud-workshop/user-010.pdf",
    issued_at: "2024-09-22T10:30:00Z",
    certificate_number: "GDG-CLOUD-010",
    template: "cloud_computing",
  },
  {
    id: "cert-016",
    user_id: "user-011",
    event_id: "event-009",
    certificate_url: "https://certificates.gdg.com/women-in-tech/user-011.pdf",
    issued_at: "2024-10-15T10:00:00Z",
    certificate_number: "GDG-WIT-011",
    template: "women_in_tech",
  },
  {
    id: "cert-017",
    user_id: "user-012",
    event_id: "event-011",
    certificate_url:
      "https://certificates.gdg.com/web3-hack-night/user-012.pdf",
    issued_at: "2025-02-03T10:00:00Z",
    certificate_number: "GDG-WEB3-012",
    template: "web3_hack",
  },
  {
    id: "cert-018",
    user_id: "user-013",
    event_id: "event-006",
    certificate_url:
      "https://certificates.gdg.com/flutter-forward/user-013.pdf",
    issued_at: "2025-02-12T10:00:00Z",
    certificate_number: "GDG-FLT-013",
    template: "flutter_forward",
  },
  {
    id: "cert-019",
    user_id: "user-015",
    event_id: "event-015",
    certificate_url: "https://certificates.gdg.com/kotlin-conf/user-015.pdf",
    issued_at: "2025-03-27T10:00:00Z",
    certificate_number: "GDG-KOT-015",
    template: "kotlin_conf",
  },
];
export const pastEvents = [
  {
    id: "event-001",
    title: "SpiderCraft 2025",
    description:
      "SPIDER CRAFT 2025: WHERE TECH MET FUN! Still buzzing from the energy of Spider Craft 2025! An unforgettable workshop where creativity met technology.",
    date: "12 NOV 2024",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=2070&auto=format&fit=crop",
    tags: ["Web Development", "Workshop"],
    tagColor: "#FFC20E",
  },
  {
    id: "event-002",
    title: "AI/ML Bootcamp",
    description:
      "Deep dive into Artificial Intelligence and Machine Learning. Participants learned neural networks, deep learning fundamentals, and built real-world AI projects.",
    date: "25 OCT 2024",
    image:
      "https://images.unsplash.com/photo-1555255707-c07966088b7b?q=80&w=2070&auto=format&fit=crop",
    tags: ["Artificial Intelligence", "Machine Learning"],
    tagColor: "#4285F4",
  },
  {
    id: "event-003",
    title: "Cloud Computing Workshop",
    description:
      "Mastered Google Cloud Platform essentials. From cloud architecture to serverless deployment, participants gained hands-on experience with modern cloud technologies.",
    date: "18 SEP 2024",
    image:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop",
    tags: ["Cloud Computing", "GCP"],
    tagColor: "#34A853",
  },
  {
    id: "event-004",
    title: "Android Development Hackathon",
    description:
      "24 hours of intense coding, creativity, and innovation. Teams built amazing Android applications and competed for exciting prizes with mentorship from industry experts.",
    date: "05 AUG 2024",
    image:
      "https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?q=80&w=2070&auto=format&fit=crop",
    tags: ["Android", "Hackathon"],
    tagColor: "#EA4335",
  },
  // Add to `pastEvents`
  {
    id: "event-005",
    title: "DSA Marathon 2024",
    description:
      "Non-stop problem-solving session where participants tackled challenging DSA problems with mentors.",
    date: "30 AUG 2024",
    image:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    tags: ["DSA", "Marathon"],
    tagColor: "#9B59B6",
  },
  {
    id: "event-006",
    title: "Git & Open Source Jam",
    description:
      "Students made their first open-source PRs and learned proper Git workflows.",
    date: "10 SEP 2024",
    image:
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=2070&auto=format&fit=crop",
    tags: ["Open Source", "Tools"],
    tagColor: "#2ECC71",
  },
  {
    id: "event-007",
    title: "Women in Tech Panel",
    description:
      "Panel featuring women engineers sharing insights on careers, leadership, and balance.",
    date: "10 OCT 2024",
    image:
      "https://images.unsplash.com/photo-1551836022-4c4c79ecde5e?q=80&w=2070&auto=format&fit=crop",
    tags: ["Diversity", "Panel"],
    tagColor: "#F39C12",
  },
  {
    id: "event-008",
    title: "DevOps for Beginners",
    description:
      "Students explored CI/CD pipelines, containers, and monitoring in a hands-on lab.",
    date: "05 NOV 2024",
    image:
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=2070&auto=format&fit=crop",
    tags: ["DevOps", "Cloud"],
    tagColor: "#1ABC9C",
  },
  {
    id: "event-009",
    title: "Campus Code Retreat",
    description:
      "A full-day practice event focused on pair programming and refactoring exercises.",
    date: "20 JUL 2024",
    image:
      "https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?q=80&w=2070&auto=format&fit=crop",
    tags: ["Practice", "Clean Code"],
    tagColor: "#34495E",
  },
  {
    id: "event-010",
    title: "Intro to Cybersecurity",
    description:
      "An introductory workshop on security principles, OWASP Top 10, and safe coding.",
    date: "28 JUN 2024",
    image:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070&auto=format&fit=crop",
    tags: ["Cybersecurity", "Workshop"],
    tagColor: "#8E44AD",
  },
  {
    id: "event-011",
    title: "Firebase in a Day",
    description:
      "Rapid prototyping session building full-stack apps with Firebase backend.",
    date: "15 MAY 2024",
    image:
      "https://images.unsplash.com/photo-1523475472560-d2df97ec485c?q=80&w=2070&auto=format&fit=crop",
    tags: ["Firebase", "Backend"],
    tagColor: "#F5B041",
  },
  {
    id: "event-012",
    title: "Intro to Figma for Devs",
    description:
      "Designers and developers collaborated to learn Figma basics and handoff workflows.",
    date: "02 APR 2024",
    image:
      "https://images.unsplash.com/photo-1522204502588-1b53ff3f8c3a?q=80&w=2070&auto=format&fit=crop",
    tags: ["Design", "Collaboration"],
    tagColor: "#E84393",
  },
  {
    id: "event-013",
    title: "ML Study Jam",
    description:
      "Multi-week study jam that concluded with a recap and Q&A session.",
    date: "10 MAR 2024",
    image:
      "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=2070&auto=format&fit=crop",
    tags: ["Machine Learning", "Study Jam"],
    tagColor: "#4285F4",
  },
  {
    id: "event-014",
    title: "Web Basics Bootcamp",
    description:
      "Beginner-friendly bootcamp covering HTML, CSS, and JS fundamentals.",
    date: "20 FEB 2024",
    image:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    tags: ["Web Development", "Beginner"],
    tagColor: "#FFC20E",
  },
];
export const upcomingEvents = [
  {
    id: "event-005",
    title: "DevFest Nagpur 2025",
    description:
      "The biggest developer festival of the year! Join us for a day of learning, networking, and celebrating technology with keynotes, workshops, and community connections.",
    date: "15 JAN 2025",
    time: "09:00 AM", // ⬅️ added time field
    image:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=2070&auto=format&fit=crop",
    tags: ["Conference", "Networking"],
    tagColor: "#FBBC04",
    location: "Grand Convention Center, Nagpur",
    registrationOpen: true,
    spotsLeft: 158,
  },
];
